### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by gentunian** [aghie/uuusa#1]
Hi! :)

trying to build from source gives me:

```
[ERROR] Failed to execute goal on project samulan: Could not resolve dependencies for project org.grupolys.samulan:samulan:jar:0.1.1: Could not find artifact org.grupolys:nlputils:jar:0.0.1-SNAPSHOT -> [Help 1]
```

where is that artifact located?

**Comment by aghie** [comment]
My mistake, sorry. nlputils was just in my local repository and forgot to include it. Put it now as a part of the source code as a quick solution. It's working on my machine now.

**Comment by gentunian** [comment]
build! :)

**Comment by gentunian** [comment]
hi again :) this issue cames when trying to run the generated jar:

```
$ java -Dfile.encoding=UTF-8 -jar -Xmx2g target/samulan-0.1.1.jar 
no main manifest attribute, in target/samulan-0.1.1.jar
```

Any special way to compile the jar?

**Comment by aghie** [comment]
hi, what command are you using to create the .jar? From a first look it looks like you are creating a non-standalone version of the jar. "mvn assembly:assembly" seems to be working for me.

**Comment by gentunian** [comment]
same:

```
java -jar target/samulan-0.1.1.jar 
no main manifest attribute, in target/samulan-0.1.1.jar
```

This works:
```
java -jar target/samulan-0.1.1-jar-with-dependencies.jar 
usage: Samulan [-h] [-i INPUT] [-c CONLL] -s SENTIDATA [-e ENCODING] [-f FILTERING] [-r RULES] [-o OUTPUT] [-v VERBOSE] [-sc SCALE] -p PROPERTIES
               [-spf PATH_SAVED_PARSER_FILE]
```

could you update README with that info how to build that jar? And as a side note, is this jar the same from the grupolys site? http://grupolys.org/software/UUUSA/samulan-0.1.0.jar

That jar has 286MB.

**Comment by aghie** [comment]
Tried to make it clear now in the README how to build with mvn.

Yes, the code is essentially the same. samulan-0.1.0.jar in the local repository is essentially samulan-0.1.1-jar-with-dependencies.jar. Version 0.1.1 added the option of saving the parsed output to a file. The version in the local repository takes more space because inside there are already some pre-trained models for tagging and parsing, etc (that you can download from the local repository too). But here in github I just plan to keep the source code. Will add some comments on this.
